export const ALL_TOPICS = [
  "Artificial Intelligence",
  "Technology",
  "Markets",
  "Politics",
  "Geopolitics",
  "Climate Change",
  "Healthcare",
  "Business",
  "Cybersecurity",
  "Science",
  "Energy",
  "Defense",
  "Space",
  "Crypto",
  "Sports",
  "Entertainment",
  "Labor",
  "Real Estate",
  "Education",
  "Transportation",
];
